### ISSUE TITLE
Geany Crashes on split window activity - GTK3

### ISSUE THREAD

**Issue by sagarchalise** [geany/geany#1385]
Segmentation fault when split window is used with some activity like editing. I am using the gtk3 build on ubuntu.

BackTrace:

```
Thread 1 "geany" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a02eed in Document::MovePositionOutsideChar (this=0x651dd0, pos=291,
    moveDir=1, checkLineEnd=false) at src/Document.cxx:628
628             if (pos >= Length())


#0  0x00007ffff7a02eed in Document::MovePositionOutsideChar (this=0x651dd0,
    pos=291, moveDir=1, checkLineEnd=false) at src/Document.cxx:628
#1  0x00007ffff7a043bb in Document::CountCharacters (this=0x651dd0,
    startPos=<optimized out>, endPos=292) at src/Document.cxx:1399
#2  0x00007ffff79e8938 in ScintillaGTKAccessible::Notify (this=0x2340610,
    nt=0x7fffffffc620) at gtk/ScintillaGTKAccessible.cxx:866
#3  0x00007ffff79e8d47 in ScintillaGTKAccessible::SciNotify (
    widget=<optimized out>, code=<optimized out>, nt=<optimized out>,
    data=<optimized out>) at gtk/ScintillaGTKAccessible.h:33
#4  0x00007ffff55bbfa5 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff55cdfc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff55d6d5c in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff55d708f in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff79decdf in ScintillaGTK::NotifyParent (this=0x2cf24f0, scn=...)
    at gtk/ScintillaGTK.cxx:1088
---Type <return> to continue, or q <return> to quit---
#9  0x00007ffff7a19aaa in Editor::NotifyModified (this=0x2cf24f0, mh=...)
    at src/Editor.cxx:2713
#10 0x00007ffff7a058ae in Document::NotifyModified (this=this@entry=0x2cee530,
    mh=...) at src/Document.cxx:2267
#11 0x00007ffff7a07540 in Document::DeleteChars (this=0x2cee530, pos=291, len=1)
    at src/Document.cxx:1054
#12 0x00007ffff7a12cf7 in Editor::DelCharBack (this=0x35fce20,
    allowLineStartDeletion=true) at src/Editor.cxx:2265
#13 0x00007ffff7a16a4a in Editor::KeyCommand (this=0x35fce20,
    iMessage=<optimized out>) at src/Editor.cxx:3726
#14 0x00007ffff7a20126 in Editor::WndProc (this=0x35fce20, iMessage=2326,
    wParam=0, lParam=0) at src/Editor.cxx:7478
#15 0x00007ffff79e48a6 in ScintillaGTK::WndProc (this=0x35fce20,
    iMessage=<optimized out>, wParam=<optimized out>, lParam=0)
    at gtk/ScintillaGTK.cxx:862
#16 0x00007ffff7a0e7af in Editor::KeyDownWithModifiers (this=0x35fce20, key=8,
    modifiers=0, consumed=0x7fffffffcba7) at src/Editor.cxx:3842
#17 0x00007ffff79e1973 in ScintillaGTK::KeyThis (this=0x35fce20, event=0x360c370)
---Type <return> to continue, or q <return> to quit---
    at gtk/ScintillaGTK.cxx:2074
#18 0x00007ffff6c28fac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff55bbeff in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff55ce56e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff55d67f9 in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff55d708f in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff6d66c5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff6d86cdb in gtk_window_propagate_key_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff6d8a15b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff6c28fac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff55bbfa5 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff55ce56e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff55d67f9 in g_signal_emit_valist ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff55d708f in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff6d66c5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff6c264c9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff6c281bc in gtk_main_do_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff6795ca2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#35 0x00007ffff50e1197 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff50e13f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff50e1712 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff6c27395 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff79a0427 in main_lib (argc=1, argv=0x7fffffffd948) at libmain.c:1233
#40 0x00007ffff7365830 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#41 0x00000000004005d9 in _start ()
```

**Comment by elextr** [comment]
Are you using Git Head version of Geany? There were some patches to Scintilla accessible stuff that I think were added after last release of Geany.

**Comment by sagarchalise** [comment]
Yes

**Comment by elextr** [comment]
Ok, @b4n, catch!! :)

**Comment by b4n** [comment]
Okay, I have no idea what's actually leading to a failing code path, but the fix makes sense so I guess for some reason the accessible object is switched over somehow.

Anyway, you should find the fix in master.  Thanks for the report!

**Comment by rashidtab** [comment]
I have the same error. I have a 21 inch screen and 27 inch screen.

**Comment by elextr** [comment]
@rashidtab what version or geany and what version of GTK are you using?
