### ISSUE TITLE
Could not load libvte.so, embedded terminal support disabled

### ISSUE THREAD

**Issue by xorobabel** [geany/geany#1955]
I recently installed Kubuntu 18.04. The terminal window no longer appears in geany.

Symbolic links in /usr/lib:
libvte.so -> libvte.so.9.2800.2
libvte.so.9 -> libvte.so.9.2800.2

And in /usr/lib/x86_64-linx-gnu:
libgtk-3.so.0 -> libgtk-3.so.0.2200.30

Running with run -v in gdb produces this output:

(gdb) run -v
Starting program: /usr/bin/geany -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed5bb700 (LWP 1560)]
Geany-INFO: 14:03:15.318: Geany 1.32, en_US.UTF-8
Geany-INFO: 14:03:15.318: GTK 3.22.30, GLib 2.56.2
Geany-INFO: 14:03:15.318: System data dir: /usr/share/geany
Geany-INFO: 14:03:15.318: User config dir: /home/xorobabel/.config/geany
Geany-INFO: 14:03:15.448: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: 14:03:15.479: Added filetype Clojure (61).
Geany-INFO: 14:03:15.479: Added filetype Genie (62).
Geany-INFO: 14:03:15.479: Added filetype Graphviz (63).
Geany-INFO: 14:03:15.480: Added filetype Cython (64).
Geany-INFO: 14:03:15.480: Added filetype JSON (65).
Geany-INFO: 14:03:15.480: Added filetype CUDA (66).
Geany-INFO: 14:03:15.480: Added filetype Scala (67).
Geany-INFO: 14:03:15.480: Added filetype Arduino (68).
Geany-INFO: 14:03:15.488: Could not load libvte.so, embedded terminal support disabled

Running with run -v --vte-lib /usr/lib/libvte.so.9 produces this output:

(gdb) run -v --vte-lib /usr/lib/libvte.so.9
Starting program: /usr/bin/geany -v --vte-lib /usr/lib/libvte.so.9
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed5bb700 (LWP 2076)]
Geany-INFO: 14:08:19.377: Geany 1.32, en_US.UTF-8
Geany-INFO: 14:08:19.377: GTK 3.22.30, GLib 2.56.2
Geany-INFO: 14:08:19.377: System data dir: /usr/share/geany
Geany-INFO: 14:08:19.377: User config dir: /home/xorobabel/.config/geany
Geany-INFO: 14:08:19.508: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: 14:08:19.536: Added filetype Clojure (61).
Geany-INFO: 14:08:19.536: Added filetype Genie (62).
Geany-INFO: 14:08:19.536: Added filetype Graphviz (63).
Geany-INFO: 14:08:19.536: Added filetype Cython (64).
Geany-INFO: 14:08:19.536: Added filetype JSON (65).
Geany-INFO: 14:08:19.536: Added filetype CUDA (66).
Geany-INFO: 14:08:19.536: Added filetype Scala (67).
Geany-INFO: 14:08:19.536: Added filetype Arduino (68).
Geany-INFO: 14:08:19.619: Loaded libvte from /usr/lib/libvte.so.9

Thread 1 "geany" received signal SIGSEGV, Segmentation fault.
0x00007ffff6d7e485 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
(gdb) bt
#0  0x00007ffff6d7e485 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#1  0x00007ffff55928f8 in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff5573748 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff5574ee5 in g_object_new_with_properties () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff5575961 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff79c9cc4 in  () at /usr/lib/x86_64-linux-gnu/libgeany.so.0
#6  0x00007ffff7992f95 in main_lib () at /usr/lib/x86_64-linux-gnu/libgeany.so.0
#7  0x00007ffff7330b97 in __libc_start_main (main=
    0x555555554650, argc=4, argv=0x7fffffffdee8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffded8) at ../csu/libc-start.c:310
#8  0x000055555555468a in  ()

**Comment by xorobabel** [comment]
That did it. Thank you.
