### ISSUE TITLE
Geany 1.35 - bug in updatechecker plugin on win10

### ISSUE THREAD

**Issue by djhenderson** [geany/geany#2137]
When I saw the announcement for Geany 1.35, I uninstalled 1.34 plugins and 1.34. I found a user only install and also uninstalled it. Then I installed Geany 1.35 and plugins on Win10 as administrator.

I used plugin manager to enable the updatechecker plugin.

I clicked on the check for updates menu item.

Geany closed immediately. On restarting, Geany closed again. And same again. I uninstalled and reinstalled the plugins, this time not enabling the updatechecker plugin, to restore normal operations.

The Windows event viewer shows an error and an information message. The error text is:

```
Faulting application name: Geany.exe, version: 1.35.0.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.17763.404, time stamp: 0x3424aead
Exception code: 0x80000003
Fault offset: 0x001502d2
Faulting process id: 0x1cd8
Faulting application start time: 0x01d4fde9f8497578
Faulting application path: C:\Program Files (x86)\Geany\bin\Geany.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4e431283-3912-4af8-a9b7-29fe7840618d
Faulting package full name: 
Faulting package-relative application ID: 
```
I can't seem to attach the WER report. But it may not be useful to anyone outside Microsoft.

My WAG is that geany or the plugin is making a bad windows API call.

Any advice on how to help solve this problem is welcome.

THX
Doug

**Comment by eht16** [comment]
Confirmed, gdb backtrace:
```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x64bfb93e in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
(gdb) bt
#0  0x64bfb93e in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
#1  0x64bfc6d5 in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
#2  0x64bfc867 in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
#3  0x6166384c in ?? () from c:\Program Files (x86)\Geany\bin\libgio-2.0-0.dll
#4  0x6810b822 in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#5  0x6810d2a9 in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#6  0x6810d343 in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#7  0x616638ad in ?? () from c:\Program Files (x86)\Geany\bin\libgio-2.0-0.dll
#8  0x676c1f06 in ?? () from c:\Program Files (x86)\Geany\lib\gio\modules\libgiognomeproxy.dll
#9  0x6812a44a in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#10 0x6810b4be in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#11 0x6810cbac in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#12 0x6810d374 in ?? () from c:\Program Files (x86)\Geany\bin\libgobject-2.0-0.dll
#13 0x615f6290 in ?? () from c:\Program Files (x86)\Geany\bin\libgio-2.0-0.dll
#14 0x615f7619 in ?? () from c:\Program Files (x86)\Geany\bin\libgio-2.0-0.dll
#15 0x6160b4cf in ?? () from c:\Program Files (x86)\Geany\bin\libgio-2.0-0.dll
#16 0x671f3255 in ?? () from c:\Program Files (x86)\Geany\bin\libsoup-2.4-1.dll
#17 0x671f6b04 in ?? () from c:\Program Files (x86)\Geany\bin\libsoup-2.4-1.dll
#18 0x671f7270 in ?? () from c:\Program Files (x86)\Geany\bin\libsoup-2.4-1.dll
#19 0x671f72db in ?? () from c:\Program Files (x86)\Geany\bin\libsoup-2.4-1.dll
#20 0x64bf6191 in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
#21 0x64bf6548 in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
#22 0x64bf69e1 in ?? () from c:\Program Files (x86)\Geany\bin\libglib-2.0-0.dll
#23 0x61a4bd09 in ?? () from c:\Program Files (x86)\Geany\bin\libgtk-win32-2.0-0.dll
#24 0x6a182fb7 in main_lib () from c:\Program Files (x86)\Geany\bin\libgeany-0.dll
#25 0x004015e0 in ?? ()
#26 0x0040138b in ?? ()
#27 0x769b343d in KERNEL32!BaseThreadInitThunk () from C:\Windows\syswow64\kernel32.dll
#28 0x77af9802 in ntdll!RtlInitializeExceptionChain () from C:\Windows\system32\ntdll.dll
#29 0x77af97d5 in ntdll!RtlInitializeExceptionChain () from C:\Windows\system32\ntdll.dll
#30 0x00000000 in ?? ()
```

Unfortunately, I don't have debug symbols on Windows, so we only see it's crashing somewhere in GLib, maybe triggered by libsoup, maybe triggered by the UpdateChecker plugin.

I just tried building the libsoup package but that failed with strange syntax errors during compilation.

No idea how to debug this :(.
