### ISSUE TITLE
Hang on file save

### ISSUE THREAD

**Issue by elextr** [geany/geany#853]
21:38:28: Geany INFO		: Geany 1.27 (git >= 27628c0), en_AU.UTF-8
21:38:28: Geany INFO		: GTK 3.10.8, GLib 2.40.2

latest git d1fcd9f with the @b4n pr #852 

Saved a new file to home directory the tab text changed from red to black and geany just hung, no UI response.  Unfortunately it went away just as I attached gdb :(

I also have had a previous hang in the last few days, again I think just after a new file save but didn't pay much attention then, paid more attention the second time it happened.  The first hang was before #852 so I think that is unlikely to be the culprit.

This doesn't seem to be related to previously reported "hangs" "crashes" or "freezes" which seem to be dodgy filesystems or similar or MS windows.  This is Linux Mint 17.3 (based on Ubuntu LTS) on a local disk and no error messages in the logs, and the file saved fine.

**Comment by codebrainz** [comment]
I wonder if it's related to being a GTK+ 3 build.

**Comment by elextr** [comment]
Have been running the gtk3 build for months, some issues see #807, but no hangs.

**Comment by elextr** [comment]
And to answer my own question (though I don't think it is relevant as the file save finished) `use_gio_unsafe_file_saving` only, no plugins.

**Comment by elextr** [comment]
Another hang, pasted the string from http://sourceforge.net/p/geany/feature-requests/120/ into an empty doc and saved as .pl file and hung.

Interesting that it happened just after saving a new file again.  Maybe thats a pattern.

**Comment by codebrainz** [comment]
Where was it stuck when you attached the debugger to it?

**Comment by elextr** [comment]
Didn't get to do that, maybe next time

**Comment by elextr** [comment]
This happened again.  Current master plus techee's highlight patch.

Saving a two line file to /tmp/untitled.py which succeeded but Geany never came back.

Not sure the backtrace is useful, its just in the main loop.  Continued several times but didn't catch any Geany activity.  Here is one such bt just for reference.

(gdb) bt
#0  0x00007f025297f629 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f025297f979 in g_mutex_lock () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f025293ded5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f025293e30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f0254192e55 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007f0254d5a551 in main_lib (argc=1, argv=0x7fffc7075c98) at libmain.c:1229
#6  0x00007f0254724ec5 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00000000004005fe in _start ()
(gdb)

**Comment by b4n** [comment]
Not that it's really likely to help, maybe you could install debugging symbols for GLib (and GTK) so we can at least have a more meaningful backtrace for them.
